export const DATA = {
  name: "Aditya Singh",
  firstName: "Aditya",
  headline: "Build high-perf systems. Ship agentic AI.",
  pill: "Final year @ IIIT Ranchi",
  bio: "Final year @ IIIT Ranchi. Building high-perf web apps, backend architecture & cloud infrastructure. Currently deep in Devops & Agentic AI.",
  experience: [
    {
      company: "Tutedude",
      role: "Software Engineer Intern",
      date: "Aug 2026 - Present",
      logo: "/tutedude.png",
      href: "https://tutedude.com",
    },
    {
      company: "Draviya",
      role: "Founding Engineer (Full Stack)",
      date: "Dec 2025 - Present",
      logo: "/draviya.png",
      href: "https://draviya.com",
    },
    {
      company: "House of Geeks, IIIT Ranchi",
      role: "Software Dev Wing Lead & Coordinator",
      date: "Mar 2025 - Sep 2026",
      logo: "/hog.png",
      href: "https://houseofgeeks.netlify.app/",
    },
    {
      company: "Hello Hospital",
      role: "Software Engineer Intern",
      date: "Jun 2026 - Jul 2026",
      logo: "/hellohospital.svg",
      href: "https://hellohospital.in",
    },
  ],
  education: [
    {
      institution: "IIIT Ranchi",
      degree: "Bachelor of Technology in Electronics and Communication",
      date: "2023 - 2027",
      logo: "/iiit-ranchi.png",
    },
  ],
  skills: [
    "Rust", "C++", "TypeScript", "JavaScript", "SQL", "Python",
    "React.js", "Next.js", "Express.js", "TailwindCSS", "FastAPI", "Hono",
    "AWS", "Docker", "PostgreSQL", "MongoDB", "Redis", "Kubernetes", "Prometheus", "Grafana", "BullMQ",
    "Langchain", "Langgraph", "Langsmith",
  ],
  projects: [
    {
      title: "InkLink",
      date: "2025",
      description: "Real-time collaborative workspace with Excalidraw-like features. Draw, plan, and brainstorm together using shared TypeScript interfaces.",
      tech: ["Next.js", "Express", "WebSockets", "BullMQ"],
      link: "https://github.com/iaadi4/inklink",
      image: "/projects/inklink.png",
    },
    {
      title: "Ora",
      date: "2025",
      description: "Voice journaling app with AI transcription and emotion analysis. Features secure authentication via BetterAuth, cloud storage on AWS S3.",
      tech: ["Next.js", "FastAPI", "OpenAI Whisper"],
      link: "https://github.com/iaadi4/ora",
      image: "/projects/ora.png",
    },
    {
      title: "SEO Boost",
      date: "2025",
      description: "Instant technical SEO audit tool. Run a professional audit in seconds and get a beautiful, actionable report.",
      tech: ["Next.js", "TypeScript", "SEO", "Analytics"],
      link: "https://github.com/iaadi4/SeoBoost",
      image: "/projects/seoboost.png",
    },
    {
      title: "FocusOS",
      date: "2025",
      description: "Master your digital life. Combines powerful site blocking, browsing analytics, and flow-state tools into one beautiful Firefox extension dashboard.",
      tech: ["TypeScript", "WebExtension", "Firefox"],
      link: "https://github.com/iaadi4/FocusOS",
      image: "/projects/focusos.png",
    },
  ],
  blog: {
    title: "Stop Querying Your Database for Usernames: The Bouncer Pattern",
    date: "Jan 2026",
    link: "https://medium.com/@adityasingh40675/stop-querying-your-database-for-usernames-the-bouncer-pattern-b06afcd1fe82",
    tags: ["Backend", "PostgreSQL", "Optimization"],
  },
};
